name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Örnek: v1.0.0

permissions:
  contents: write  # GITHUB_TOKEN ile release oluşturmak için

jobs:
  build-and-release:
    name: Build & Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binary
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/simple-idm-${{ matrix.goos }}-${{ matrix.goarch }}$EXT

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/simple-idm-${{ matrix.goos }}-${{ matrix.goarch }}
            dist/simple-idm-${{ matrix.goos }}-${{ matrix.goarch }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
